from typing import Literal

FFTLIB: Literal[
    "NUMPY", "SCIPY", "PYFFTW", "MKLFFT"
] = "PYFFTW"

FFT_METHOD: Literal[
    "SLAB", "STICKS"
] = "SLAB"

FFT_NUM_THREADS: int = 1


PYFFTW_PLANNER_EFFORT: Literal[
    "FFTW_ESTIMATE", "FFTW_MEASURE", "FFTW_PATIENT", "FFTW_EXHAUSTIVE"
] = "FFTW_PATIENT"


